# Uncomment the next line to define a global platform for your project
# platform :ios, '10'

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for editorTest
#  pod 'iOSPhotoEditor' #, :git => 'https://github.com/M-Hamed/photo-editor.git'
  pod 'iOSPhotoEditor', :path => '../'

end
